### ISSUE TITLE
Limit neighborhoods geoms to area of interest

### ISSUE THREAD

**Issue by rgdonohue** [annaleebard/seattle-weekender-map#4]
Just the main part of Seattle there with the art points? If the rest aren't part of the story we don't need them.

**Comment by annaleebard** [comment]
Good thought. If it's a "weekender" map most likely we won't be all over the suburbs. I'll trim them down.

**Comment by annaleebard** [comment]
trimmed the neighborhoods down to the proper city limits - could focus map more if needed.
